apiVersion: apps/v1
kind: Deployment
metadata:
  name: rusell-elasticsearch-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rusell-elasticsearch
  template:
    metadata:
      labels:
        app: rusell-elasticsearch
    spec:
      containers:
        - name: es01
          image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: node.name
              value: es01
            - name: cluster.name
              value: rusell-logging
            - name: cluster.initial_master_nodes
              value: es01
          ports:
            - containerPort: 9200
              name: es01-port
          volumeMounts:
            - name: rusell-elastic-search-data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: rusell-elastic-search-data
          persistentVolumeClaim:
            claimName: rusell-elastic-search-data-claim
---
apiVersion: v1
kind: Service
metadata:
  name: rusell-elasticsearch-service
spec:
  type: ClusterIP
  selector:
    app: rusell-elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
      name: es01-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rusell-kibana-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rusell-kibana
  template:
    metadata:
      labels:
        app: rusell-kibana
    spec:
      containers:
        - name: kibana01
          image: docker.elastic.co/kibana/kibana:7.9.0
          env:
            - name: ELASTICSEARCH_URL
              value: http://rusell-elasticsearch-service:9200
            - name: ELASTICSEARCH_HOSTS
              value: http://rusell-elasticsearch-service:9200
          ports:
            - containerPort: 5601
              name: kibana-port
---
apiVersion: v1
kind: Service
metadata:
  name: rusell-logging-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: rusell-kibana
  ports:
    - port: 5601
      targetPort: 5601
      name: kibana-port
