// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rusell.Routes.Shared.Infrastructure.Persistence.EntityFramework;

#nullable disable

namespace Rusell.Routes.Migrations
{
    [DbContext(typeof(RoutesDbContext))]
    [Migration("20211217231148_AddAddress")]
    partial class AddAddress
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rusell.Routes.Addresses.Domain.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("Rusell.Routes.Companies.Domain.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("Rusell.Routes.Domain.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid>("FromId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_id");

                    b.Property<Guid>("ToId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_id");

                    b.HasKey("Id")
                        .HasName("pk_routes");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_routes_company_id");

                    b.HasIndex("FromId")
                        .HasDatabaseName("ix_routes_from_id");

                    b.HasIndex("ToId")
                        .HasDatabaseName("ix_routes_to_id");

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("Rusell.Routes.Addresses.Domain.Address", b =>
                {
                    b.OwnsOne("Rusell.Routes.Addresses.Domain.City", "City", b1 =>
                        {
                            b1.Property<Guid>("AddressId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("city");

                            b1.HasKey("AddressId");

                            b1.ToTable("addresses");

                            b1.WithOwner()
                                .HasForeignKey("AddressId")
                                .HasConstraintName("fk_addresses_addresses_id");
                        });

                    b.OwnsOne("Rusell.Routes.Addresses.Domain.Country", "Country", b1 =>
                        {
                            b1.Property<Guid>("AddressId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("country");

                            b1.HasKey("AddressId");

                            b1.ToTable("addresses");

                            b1.WithOwner()
                                .HasForeignKey("AddressId")
                                .HasConstraintName("fk_addresses_addresses_id");
                        });

                    b.OwnsOne("Rusell.Routes.Addresses.Domain.State", "State", b1 =>
                        {
                            b1.Property<Guid>("AddressId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("state");

                            b1.HasKey("AddressId");

                            b1.ToTable("addresses");

                            b1.WithOwner()
                                .HasForeignKey("AddressId")
                                .HasConstraintName("fk_addresses_addresses_id");
                        });

                    b.Navigation("City")
                        .IsRequired();

                    b.Navigation("Country")
                        .IsRequired();

                    b.Navigation("State")
                        .IsRequired();
                });

            modelBuilder.Entity("Rusell.Routes.Companies.Domain.Company", b =>
                {
                    b.OwnsOne("Rusell.Routes.Companies.Domain.CompanyName", "Name", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("name");

                            b1.HasKey("CompanyId");

                            b1.ToTable("companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId")
                                .HasConstraintName("fk_companies_companies_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Rusell.Routes.Domain.Route", b =>
                {
                    b.HasOne("Rusell.Routes.Companies.Domain.Company", "Company")
                        .WithMany("Routes")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_routes_companies_company_temp_id");

                    b.HasOne("Rusell.Routes.Addresses.Domain.Address", "From")
                        .WithMany("Routes1")
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_routes_addresses_from_id1");

                    b.HasOne("Rusell.Routes.Addresses.Domain.Address", "To")
                        .WithMany("Routes2")
                        .HasForeignKey("ToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_routes_addresses_to_id1");

                    b.OwnsOne("Rusell.Routes.Domain.Cost", "Cost", b1 =>
                        {
                            b1.Property<Guid>("RouteId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Value")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("cost");

                            b1.HasKey("RouteId");

                            b1.ToTable("routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId")
                                .HasConstraintName("fk_routes_routes_id");
                        });

                    b.OwnsOne("Rusell.Routes.Domain.IsCustomerDroppedOffAtHome", "IsCustomerDroppedOffAtHome", b1 =>
                        {
                            b1.Property<Guid>("RouteId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool>("Value")
                                .HasColumnType("boolean")
                                .HasColumnName("is_customer_dropped_off_at_home");

                            b1.HasKey("RouteId");

                            b1.ToTable("routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId")
                                .HasConstraintName("fk_routes_routes_id");
                        });

                    b.OwnsOne("Rusell.Routes.Domain.IsCustomerPickedUpAtHome", "IsCustomerPickedUpAtHome", b1 =>
                        {
                            b1.Property<Guid>("RouteId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool>("Value")
                                .HasColumnType("boolean")
                                .HasColumnName("is_customer_picked_up_at_home");

                            b1.HasKey("RouteId");

                            b1.ToTable("routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId")
                                .HasConstraintName("fk_routes_routes_id");
                        });

                    b.Navigation("Company");

                    b.Navigation("Cost")
                        .IsRequired();

                    b.Navigation("From");

                    b.Navigation("IsCustomerDroppedOffAtHome")
                        .IsRequired();

                    b.Navigation("IsCustomerPickedUpAtHome")
                        .IsRequired();

                    b.Navigation("To");
                });

            modelBuilder.Entity("Rusell.Routes.Addresses.Domain.Address", b =>
                {
                    b.Navigation("Routes1");

                    b.Navigation("Routes2");
                });

            modelBuilder.Entity("Rusell.Routes.Companies.Domain.Company", b =>
                {
                    b.Navigation("Routes");
                });
#pragma warning restore 612, 618
        }
    }
}
